name: smallgroup
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- flask
- tinydb
- pytest
- python=3.6
- boto3
- awscli
- ipython
- mypy
- flake8
- pandas
- python-dotenv
- psycopg2
- sqlalchemy
- flask-sqlalchemy
- pyjanitor
- black
- holoviews
- bokeh
