name: smallgroup
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- flask
- pytest
- python=3.6
- ipython
- mypy
- flake8
- pandas
- python-dotenv
- psycopg2
- sqlalchemy
- flask-sqlalchemy
- pyjanitor
- nomkl  # added to save space on heroku
- black
- holoviews
- bokeh
